### ISSUE TITLE
    assert isinstance(new_mixin, BaseMixin)  AssertionError更新了权重吗？导致这里出错？

### ISSUE THREAD

**Issue by corkiyao** [THUDM/SwissArmyTransformer#183]
```python
[2024-09-11 14:38:37,895] [INFO] [checkpointing.py:229:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
/home/yaoyunze/anaconda3/envs/visualglm/lib/python3.8/site-packages/torch/nn/init.py:412: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
[2024-09-11 14:38:46,937] [INFO] [checkpointing.py:229:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
Traceback (most recent call last):
  File "finetune_visualglm.py", line 178, in <module>
    model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
  File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 217, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 209, in from_pretrained_base
    model = get_model(args, cls, **kwargs)
  File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 420, in get_model
    model = model_cls(args, params_dtype=params_dtype, **kwargs)
  File "finetune_visualglm.py", line 13, in __init__
    super().__init__(args, transformer=transformer, **kw_args)
  File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/model/visualglm.py", line 34, in __init__
    self.add_mixin("eva", ImageMixin(args))
  File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 116, in add_mixin
    assert isinstance(new_mixin, BaseMixin)
AssertionError
[2024-09-11 14:38:50,191] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1365959
```

**Comment by corkiyao** [comment]
> ```python
> [2024-09-11 14:38:37,895] [INFO] [checkpointing.py:229:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
> /home/yaoyunze/anaconda3/envs/visualglm/lib/python3.8/site-packages/torch/nn/init.py:412: UserWarning: Initializing zero-element tensors is a no-op
>   warnings.warn("Initializing zero-element tensors is a no-op")
> [2024-09-11 14:38:46,937] [INFO] [checkpointing.py:229:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
> Traceback (most recent call last):
>   File "finetune_visualglm.py", line 178, in <module>
>     model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
>   File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 217, in from_pretrained
>     return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
>   File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 209, in from_pretrained_base
>     model = get_model(args, cls, **kwargs)
>   File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 420, in get_model
>     model = model_cls(args, params_dtype=params_dtype, **kwargs)
>   File "finetune_visualglm.py", line 13, in __init__
>     super().__init__(args, transformer=transformer, **kw_args)
>   File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/model/visualglm.py", line 34, in __init__
>     self.add_mixin("eva", ImageMixin(args))
>   File "/home/data/yaoyunze/visualglm_pipe/VisualGLM-6B/SwissArmyTransformer/sat/model/base_model.py", line 116, in add_mixin
>     assert isinstance(new_mixin, BaseMixin)
> AssertionError
> [2024-09-11 14:38:50,191] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1365959
> ```

好吧，不小心搞错了一个import SwissArmyTransformer.sat的包
