### ISSUE TITLE
SAT fused_ema_adam_frontend error

### ISSUE THREAD

**Issue by AlphaNext** [THUDM/SwissArmyTransformer#184]
using sat in CogVideoX-2b sat sft, and has this error:
why this?
```
ninja build file /root/.cache/torch_extensions/py310_cu121/fused_ema_adam/build.ninja...
/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_ema_adam...
```

```
[2024-09-12 20:35:44,999] [INFO] [RANK 0] Finished syncing initialized parameters.
[2024-09-12 20:35:45,000] [INFO] [RANK 0] Using optimizer sat.ops.FusedEmaAdam from sat.
[2024-09-12 20:35:45,000] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.14.4, git-hash=unknown, git-branch=unknown
[2024-09-12 20:35:45,001] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter cpu_offload is deprecated use offload_optimizer instead
[2024-09-12 20:35:45,112] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/fused_ema_adam/build.ninja...
/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_ema_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF fused_ema_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_ema_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/opt/conda/lib/python3.10/site-packages/sat/ops/csrc/includes -I/opt/conda/lib/python3.10/site-packages/sat/ops/csrc/adam -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /opt/conda/lib/python3.10/site-packages/sat/ops/csrc/adam/fused_ema_adam_frontend.cpp -o fused_ema_adam_frontend.o 
FAILED: fused_ema_adam_frontend.o 
c++ -MMD -MF fused_ema_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_ema_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/opt/conda/lib/python3.10/site-packages/sat/ops/csrc/includes -I/opt/conda/lib/python3.10/site-packages/sat/ops/csrc/adam -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /opt/conda/lib/python3.10/site-packages/sat/ops/csrc/adam/fused_ema_adam_frontend.cpp -o fused_ema_adam_frontend.o 
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/TensorBase.h:14,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:38,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /opt/conda/lib/python3.10/site-packages/sat/ops/csrc/adam/fused_ema_adam_frontend.cpp:6:
/opt/conda/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later."
 #error \
  ^~~~~
ninja: build stopped: subcommand failed.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
[rank0]:     subprocess.run(
[rank0]:   File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
[rank0]:     raise CalledProcessError(retcode, process.args,
[rank0]: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/video/CogVideoX-354c906/sat/train_video.py", line 223, in <module>
[rank0]:     training_main(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 116, in training_main
[rank0]:     model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 225, in setup_model_untrainable_params_and_optimizer
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 306, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
[rank0]:     basic_optimizer = client_optimizer(model_parameters)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/sat/ops/__init__.py", line 33, in <lambda>
[rank0]:     '__call__': lambda self, *args, **kwargs: getattr(import_module(self.path), self.name)(*args, **kwargs),
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/sat/ops/fused_ema_adam.py", line 86, in __init__
[rank0]:     fused_ema_adam_cuda = FusedEmaAdamBuilder().jit_load()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/sat/ops/ops_builder/builder.py", line 480, in jit_load
[rank0]:     op_module = load(name=self.name,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1312, in load
[rank0]:     return _jit_compile(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
[rank0]:     _write_ninja_file_and_build_library(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
[rank0]:     _run_ninja_build(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
[rank0]:     raise RuntimeError(message) from e
[rank0]: RuntimeError: Error building extension 'fused_ema_adam'
E0912 20:36:06.406000 139966916675392 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 1026) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by sangaram** [comment]
I'm getting a similar issue when trying to train [Tora](https://github.com/alibaba/Tora), @AlphaNext  any suggestion to solve it ?

```
Using /home/users/asangare/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/users/asangare/.cache/torch_extensions/py310_cu121/fused_ema_adam/build.ninja...
/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_ema_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /home/users/asangare/miniforge3/envs/tora2/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_ema_adam.cuda.o.d -ccbin /home/users/asangare/miniforge3/envs/tora2/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fused_ema_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/includes -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/TH -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/THC -isystem /home/users/asangare/miniforge3/envs/tora2/include -isystem /home/users/asangare/miniforge3/envs/tora2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86 -std=c++17 -c /home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam/multi_tensor_ema_adam.cu -o multi_tensor_ema_adam.cuda.o 
FAILED: multi_tensor_ema_adam.cuda.o 
/home/users/asangare/miniforge3/envs/tora2/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_ema_adam.cuda.o.d -ccbin /home/users/asangare/miniforge3/envs/tora2/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fused_ema_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/includes -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/TH -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/THC -isystem /home/users/asangare/miniforge3/envs/tora2/include -isystem /home/users/asangare/miniforge3/envs/tora2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86 -std=c++17 -c /home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam/multi_tensor_ema_adam.cu -o multi_tensor_ema_adam.cuda.o 
nvcc warning : incompatible redefinition for option 'compiler-bindir', the last value of this option was used
<command-line>: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
[2/3] /home/users/asangare/miniforge3/envs/tora2/bin/x86_64-conda-linux-gnu-c++ -MMD -MF fused_ema_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_ema_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/includes -I/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/TH -isystem /home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/include/THC -isystem /home/users/asangare/miniforge3/envs/tora2/include -isystem /home/users/asangare/miniforge3/envs/tora2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/csrc/adam/fused_ema_adam_frontend.cpp -o fused_ema_adam_frontend.o 
ninja: build stopped: subcommand failed.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
[rank0]:     subprocess.run(
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/subprocess.py", line 526, in run
[rank0]:     raise CalledProcessError(retcode, process.args,
[rank0]: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/users/asangare/Tora/sat/train_video.py", line 413, in <module>
[rank0]:     training_main(
[rank0]:   File "/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/training/deepspeed_training.py", line 118, in training_main
[rank0]:     model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
[rank0]:   File "/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/training/deepspeed_training.py", line 227, in setup_model_untrainable_params_and_optimizer
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 313, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
[rank0]:     basic_optimizer = client_optimizer(model_parameters)
[rank0]:   File "/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/__init__.py", line 33, in <lambda>
[rank0]:     '__call__': lambda self, *args, **kwargs: getattr(import_module(self.path), self.name)(*args, **kwargs),
[rank0]:   File "/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/fused_ema_adam.py", line 86, in __init__
[rank0]:     fused_ema_adam_cuda = FusedEmaAdamBuilder().jit_load()
[rank0]:   File "/home/users/asangare/Tora/modules/SwissArmyTransformer/sat/ops/ops_builder/builder.py", line 480, in jit_load
[rank0]:     op_module = load(name=self.name,
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1312, in load
[rank0]:     return _jit_compile(
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
[rank0]:     _write_ninja_file_and_build_library(
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
[rank0]:     _run_ninja_build(
[rank0]:   File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
[rank0]:     raise RuntimeError(message) from e
[rank0]: RuntimeError: Error building extension 'fused_ema_adam'
E0730 14:42:26.609000 22375346500096 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 90927) of binary: /home/users/asangare/miniforge3/envs/tora2/bin/python3.10
Traceback (most recent call last):
  File "/home/users/asangare/miniforge3/envs/tora2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/users/asangare/miniforge3/envs/tora2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```
