### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by ge90114b** [THUDM/SwissArmyTransformer#92]
[WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\stone\AppData\Local\Temp\easy_install-gs_qn_mw\deepspeed-0.9.2\setup.py", line 162, in <module>
  File "C:\Users\stone\AppData\Local\Temp\easy_install-gs_qn_mw\deepspeed-0.9.2\setup.py", line 51, in abort
AssertionError: Unable to pre-compile async_io

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\novelaileak\SwissArmyTransformer\setup.py", line 17, in <module>
    setup(
  File "D:\anaconda\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "D:\anaconda\lib\site-packages\setuptools\command\install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
  File "D:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "D:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "D:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
    return installer(requirement)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "D:\anaconda\lib\site-packages\setuptools\command\easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "D:\anaconda\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 190, in setup_context
    with save_modules():
  File "D:\anaconda\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "D:\anaconda\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\stone\AppData\Local\Temp\easy_install-gs_qn_mw\deepspeed-0.9.2\setup.py", line 162, in <module>
  File "C:\Users\stone\AppData\Local\Temp\easy_install-gs_qn_mw\deepspeed-0.9.2\setup.py", line 51, in abort
AssertionError: Unable to pre-compile async_io
请问应该如何解决？

**Comment by Sleepychord** [comment]
One can disable async_io with DS_BUILD_AIO=0
